### PR TITLE
Added pycryptodomex python library to decrypt AES 128 streams

### PR DESCRIPTION
**Pull request by BobbyESP**
This PR fixes https://github.com/JunkFood02/Seal/issues/507 issue.

WARN: I wasn't able to test it with Seal yet! (Reason: Hadn't time)

EDIT: Tested but having the issue that's below

### CODE REVIEW

**Comment by BobbyESP** [comment]
Having the same issue that I was having in my lib:

```
File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Not found '_raw_ecb.cpython-38.so', Not found '_raw_ecb.abi3.so', Not found '_raw_ecb.so'
```

Need to do research

**Comment by bibsp** [comment]
[dvd](https://github.com/yausername/dvd)'s code might help.

**Comment by BobbyESP** [comment]
But DVD uses the same library so there's no difference in this, because the problem that we're facing now is because the pycryptodomex needs a .so file that can't be found.

**Comment by JunkFood02** [comment]
`pycryptodome` contains C codes which should be compiled from source natively in Android, and this needs to be done in a termux-package container like ffmpeg & python

**Comment by BobbyESP** [comment]
Yes, I know, thanks for the info by the way. Seems like I have to follow the build python guide and rebuild the python termux package from source. When creating that python file zipped, yausername deleted some modules that probably contained these `_raw_ecb.so` files.

**Comment by JunkFood02** [comment]
> yausername deleted some modules that probably contained these `_raw_ecb.so` files.

> pycryptodome contains C codes which should be compiled from source natively in Android, and this needs to be done in a termux-package container like ffmpeg & python

`_raw_ecb.so` is compiled from the C codes i've mentioned

**Comment by BobbyESP** [comment]
Yeah, that's it. That's why I'll rebuild the python zip with all that modules and later i try deleting some of them.

**Comment by BobbyESP** [comment]
Sorry for inactivity. I'm having a busy week at school

**Pull request closed without merging**
